import type { GameProject3D } from "./3d-game-schema";

const timestamp = "2026-08-06T00:00:00.000Z";

const transform = (x: number, y: number, z: number, scale = 1) => ({
  position: { x, y, z },
  rotation: { x: 0, y: 0, z: 0 },
  scale: { x: scale, y: scale, z: scale },
});

export const defaultProject3D: GameProject3D = {
  schemaVersion: "3d-1.0.0",
  dimension: "3d",
  meta: {
    id: "project-astral-garden",
    name: "Astral Garden",
    description: "A small PlayCanvas scene for exploring a schema-safe 3D workflow.",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  settings: {
    width: 960,
    height: 600,
    clearColor: "#101426",
    gridSize: 1,
    shadows: true,
    autoRotatePreview: false,
  },
  assets: [],
  activeSceneId: "scene-garden",
  scenes: [
    {
      id: "scene-garden",
      name: "Astral Garden",
      backgroundColor: "#101426",
      environment: {
        ambientColor: "#9aa4c8",
        exposure: 1,
      },
      entities: [
        {
          id: "camera-editor",
          name: "Editor Camera",
          parentId: null,
          kind: "camera",
          enabled: true,
          transform: transform(0, 4.5, 9),
          camera: { fov: 45, nearClip: 0.1, farClip: 1000 },
          behaviors: [],
          tags: ["camera", "editor"] ,
        },
        {
          id: "light-key",
          name: "Key Light",
          parentId: null,
          kind: "light",
          enabled: true,
          transform: {
            position: { x: 3, y: 7, z: 4 },
            rotation: { x: -35, y: 35, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
          },
          light: { kind: "directional", color: "#fff4dd", intensity: 2.2, range: 20 },
          behaviors: [],
          tags: ["lighting"],
        },
        {
          id: "light-fill",
          name: "Fill Light",
          parentId: null,
          kind: "light",
          enabled: true,
          transform: {
            position: { x: -4, y: 3, z: 1 },
            rotation: { x: -20, y: -55, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
          },
          light: { kind: "omni", color: "#8495ff", intensity: 1.3, range: 18 },
          behaviors: [],
          tags: ["lighting"],
        },
        {
          id: "ground",
          name: "Ground",
          parentId: null,
          kind: "mesh",
          enabled: true,
          transform: {
            position: { x: 0, y: -1, z: 0 },
            rotation: { x: 0, y: 0, z: 0 },
            scale: { x: 8, y: 0.2, z: 6 },
          },
          render: {
            primitive: "box",
            material: {
              color: "#323d62",
              metallic: 0.1,
              roughness: 0.86,
              opacity: 1,
              emissive: "#000000",
            },
            castShadows: false,
            receiveShadows: true,
          },
          behaviors: [],
          tags: ["environment", "ground"],
        },
        {
          id: "hero-crystal",
          name: "Hero Crystal",
          parentId: null,
          kind: "mesh",
          enabled: true,
          transform: transform(-1.35, 0.15, 0, 1.2),
          render: {
            primitive: "sphere",
            material: {
              color: "#8c7cf0",
              metallic: 0.42,
              roughness: 0.26,
              opacity: 1,
              emissive: "#171034",
            },
            castShadows: true,
            receiveShadows: true,
          },
          behaviors: [{ id: "behavior-hero-spin", type: "spin", speed: 24, axis: "y" }],
          tags: ["hero", "interactive"],
        },
        {
          id: "orbit-cube",
          name: "Orbit Cube",
          parentId: null,
          kind: "mesh",
          enabled: true,
          transform: transform(1.25, 0.25, -0.4, 1.05),
          render: {
            primitive: "box",
            material: {
              color: "#e1ce74",
              metallic: 0.12,
              roughness: 0.38,
              opacity: 1,
              emissive: "#1d1907",
            },
            castShadows: true,
            receiveShadows: true,
          },
          behaviors: [{ id: "behavior-cube-bob", type: "bob", amplitude: 0.2, speed: 1.4 }],
          tags: ["interactive"],
        },
        {
          id: "portal-ring",
          name: "Portal Ring",
          parentId: null,
          kind: "mesh",
          enabled: true,
          transform: {
            position: { x: 0.3, y: 0.25, z: -1.35 },
            rotation: { x: 78, y: 0, z: 0 },
            scale: { x: 1.15, y: 1.15, z: 1.15 },
          },
          render: {
            primitive: "torus",
            material: {
              color: "#5ed0bd",
              metallic: 0.58,
              roughness: 0.2,
              opacity: 1,
              emissive: "#0a2927",
            },
            castShadows: true,
            receiveShadows: true,
          },
          behaviors: [{ id: "behavior-ring-spin", type: "spin", speed: -32, axis: "z" }],
          tags: ["portal", "interactive"],
        },
      ],
    },
  ],
};
