import type { GameProject } from "./game-schema";

const timestamp = "2026-07-29T00:00:00.000Z";

export const defaultProject: GameProject = {
  schemaVersion: "1.0.0",
  meta: {
    id: "project-orbit-runner",
    name: "Orbit Runner",
    description: "A compact platformer template designed for manual editing and AI iteration.",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  settings: {
    width: 960,
    height: 540,
    backgroundColor: "#171827",
    gravityY: 980,
    pixelArt: false,
    scaleMode: "fit",
  },
  assets: [],
  activeSceneId: "scene-main",
  scenes: [
    {
      id: "scene-main",
      name: "Main Level",
      backgroundColor: "#171827",
      entities: [
        {
          id: "title",
          name: "Mission label",
          type: "text",
          enabled: true,
          transform: { x: 42, y: 34, rotation: 0, scaleX: 1, scaleY: 1 },
          appearance: {
            width: 380,
            height: 44,
            color: "#f2efff",
            opacity: 1,
            text: "COLLECT THE THREE SIGNALS",
            fontSize: 21,
          },
          physics: {
            enabled: false,
            static: false,
            collideWorldBounds: false,
            allowGravity: false,
            bounce: 0,
          },
          behaviors: [],
          tags: ["ui"],
        },
        {
          id: "player",
          name: "Player",
          type: "rectangle",
          enabled: true,
          transform: { x: 145, y: 390, rotation: 0, scaleX: 1, scaleY: 1 },
          appearance: {
            width: 46,
            height: 58,
            color: "#8a7cf0",
            opacity: 1,
          },
          physics: {
            enabled: true,
            static: false,
            collideWorldBounds: true,
            allowGravity: true,
            bounce: 0.05,
          },
          behaviors: [
            {
              id: "behavior-player-controller",
              type: "playerController",
              speed: 280,
              jumpVelocity: 540,
            },
            {
              id: "behavior-camera",
              type: "cameraFollow",
              lerp: 0.1,
            },
          ],
          tags: ["player"],
        },
        {
          id: "ground",
          name: "Ground",
          type: "rectangle",
          enabled: true,
          transform: { x: 480, y: 510, rotation: 0, scaleX: 1, scaleY: 1 },
          appearance: {
            width: 960,
            height: 60,
            color: "#34364d",
            opacity: 1,
          },
          physics: {
            enabled: true,
            static: true,
            collideWorldBounds: false,
            allowGravity: false,
            bounce: 0,
          },
          behaviors: [],
          tags: ["platform"],
        },
        {
          id: "platform-left",
          name: "Left Platform",
          type: "rectangle",
          enabled: true,
          transform: { x: 290, y: 390, rotation: 0, scaleX: 1, scaleY: 1 },
          appearance: {
            width: 210,
            height: 24,
            color: "#4b4e6c",
            opacity: 1,
          },
          physics: {
            enabled: true,
            static: true,
            collideWorldBounds: false,
            allowGravity: false,
            bounce: 0,
          },
          behaviors: [],
          tags: ["platform"],
        },
        {
          id: "platform-right",
          name: "Right Platform",
          type: "rectangle",
          enabled: true,
          transform: { x: 665, y: 330, rotation: 0, scaleX: 1, scaleY: 1 },
          appearance: {
            width: 230,
            height: 24,
            color: "#4b4e6c",
            opacity: 1,
          },
          physics: {
            enabled: true,
            static: true,
            collideWorldBounds: false,
            allowGravity: false,
            bounce: 0,
          },
          behaviors: [],
          tags: ["platform"],
        },
        ...[
          { id: "signal-a", name: "Signal A", x: 305, y: 345 },
          { id: "signal-b", name: "Signal B", x: 660, y: 278 },
          { id: "signal-c", name: "Signal C", x: 845, y: 444 },
        ].map(
          ({ id, name, x, y }): GameProject["scenes"][number]["entities"][number] => ({
            id,
            name,
            type: "ellipse",
            enabled: true,
            transform: { x, y, rotation: 0, scaleX: 1, scaleY: 1 },
            appearance: {
              width: 28,
              height: 28,
              color: "#e1ce74",
              opacity: 1,
            },
            physics: {
              enabled: true,
              static: true,
              collideWorldBounds: false,
              allowGravity: false,
              bounce: 0,
            },
            behaviors: [
              {
                id: `behavior-${id}`,
                type: "collectible",
                points: 100,
              },
            ],
            tags: ["collectible"],
          }),
        ),
        {
          id: "enemy",
          name: "Patrol Drone",
          type: "rectangle",
          enabled: true,
          transform: { x: 520, y: 462, rotation: 0, scaleX: 1, scaleY: 1 },
          appearance: {
            width: 44,
            height: 34,
            color: "#d36b7b",
            opacity: 1,
          },
          physics: {
            enabled: true,
            static: false,
            collideWorldBounds: true,
            allowGravity: true,
            bounce: 0,
          },
          behaviors: [
            {
              id: "behavior-patrol",
              type: "patrol",
              speed: 92,
              distance: 190,
            },
          ],
          tags: ["enemy"],
        },
      ],
    },
  ],
};

